"""empty message

Revision ID: 3e66f1e54fe5
Revises: 9b03609a3a53
Create Date: 2021-03-03 20:51:15.288136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e66f1e54fe5'
down_revision = '9b03609a3a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'seeking_venue')
    op.drop_column('venue', 'seeking_talent')
    # ### end Alembic commands ###
