"""empty message

Revision ID: 5db449ee1e56
Revises: 3e66f1e54fe5
Create Date: 2021-03-03 20:53:56.890881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db449ee1e56'
down_revision = '3e66f1e54fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE venue SET seeking_talent = 'f' WHERE seeking_talent IS NULL;")
    op.execute("UPDATE artist SET seeking_venue = 'f' WHERE seeking_venue IS NULL;")

    op.alter_column('artist', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('venue', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('artist', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
