"""empty message

Revision ID: 98684a4471e8
Revises: 9fd918b09924
Create Date: 2021-03-04 17:37:12.896411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98684a4471e8'
down_revision = '9fd918b09924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'seeking_description')
    op.drop_column('artist', 'seeking_description')
    # ### end Alembic commands ###
