"""make website not nullable

Revision ID: 9b03609a3a53
Revises: 7fe0819888b5
Create Date: 2021-03-03 20:40:25.149515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b03609a3a53'
down_revision = '7fe0819888b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE artist SET website = 'https://www.facebook.com' WHERE website IS NULL;")
    op.execute("UPDATE venue SET website = 'https://www.facebook.com' WHERE website IS NULL;")

    op.alter_column('artist', 'website',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('venue', 'website',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'website',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('artist', 'website',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
