"""empty message

Revision ID: 9fd918b09924
Revises: 5db449ee1e56
Create Date: 2021-03-04 15:29:24.213048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd918b09924'
down_revision = '5db449ee1e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('venue', sa.Column('created_date', sa.DateTime(), nullable=True))

    op.execute("UPDATE artist SET created_date = NOW()")
    op.execute("UPDATE venue SET created_date = NOW()")

    op.alter_column('artist', 'created_date', nullable=False)
    op.alter_column('venue', 'created_date', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'created_date')
    op.drop_column('artist', 'created_date')
    # ### end Alembic commands ###
