"""change table names

Revision ID: d08c4af06555
Revises: 7c9643934ffb
Create Date: 2021-02-26 14:09:26.338428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd08c4af06555'
down_revision = '7c9643934ffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('Show', 'show')
    op.rename_table('Artist', 'artist')
    op.rename_table('Venue', 'venue')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('show', 'Show')
    op.rename_table('artist', 'Artist')
    op.rename_table('venue', 'Venue')
    # ### end Alembic commands ###
